/*
  QV37 AI
  CREATOR UI

  This file creates the Creator Mode controls.
  It works together with creator.js.

  IMPORTANT:
  Creator access is still verified by /api/me.
*/

(function () {

  "use strict";


  /*
    WAIT UNTIL PAGE IS READY
  */

  function startCreatorUI() {

    /*
      CREATE CREATOR PANEL
    */

    if (document.getElementById("qv37-creator-panel")) {
      return;
    }


    const panel =
      document.createElement("div");

    panel.id =
      "qv37-creator-panel";

    panel.className =
      "hidden fixed inset-0 bg-black/80 backdrop-blur-sm z-[100] flex items-center justify-center p-4";


    panel.innerHTML = `

      <div class="w-full max-w-2xl bg-zinc-900 border border-zinc-800 rounded-2xl p-6 shadow-2xl">

        <div class="flex items-center justify-between mb-6">

          <div>

            <div class="text-xs text-emerald-400 font-bold">
              QV37 AI
            </div>

            <h2 class="text-2xl font-black">
              Creator Mode
            </h2>

            <p class="text-sm text-zinc-500 mt-1">
              Creator control center
            </p>

          </div>

          <button
            id="qv37-creator-close"
            class="text-zinc-500 hover:text-white text-2xl"
          >
            ×
          </button>

        </div>


        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">


          <button
            id="creator-dashboard-btn"
            class="text-left bg-zinc-950 border border-zinc-800 hover:border-emerald-500 rounded-xl p-4"
          >

            <div class="text-emerald-400 text-xl">
              📊
            </div>

            <div class="font-bold mt-2">
              Dashboard
            </div>

            <div class="text-xs text-zinc-500 mt-1">
              View creator statistics and system information.
            </div>

          </button>


          <button
            id="creator-users-btn"
            class="text-left bg-zinc-950 border border-zinc-800 hover:border-emerald-500 rounded-xl p-4"
          >

            <div class="text-emerald-400 text-xl">
              👥
            </div>

            <div class="font-bold mt-2">
              Users
            </div>

            <div class="text-xs text-zinc-500 mt-1">
              Manage and inspect QV37 users.
            </div>

          </button>


          <button
            id="creator-apps-btn"
            class="text-left bg-zinc-950 border border-zinc-800 hover:border-emerald-500 rounded-xl p-4"
          >

            <div class="text-emerald-400 text-xl">
              🚀
            </div>

            <div class="font-bold mt-2">
              Generated Apps
            </div>

            <div class="text-xs text-zinc-500 mt-1">
              View applications generated by QV37 AI.
            </div>

          </button>


          <button
            id="creator-settings-btn"
            class="text-left bg-zinc-950 border border-zinc-800 hover:border-emerald-500 rounded-xl p-4"
          >

            <div class="text-emerald-400 text-xl">
              ⚙️
            </div>

            <div class="font-bold mt-2">
              Creator Settings
            </div>

            <div class="text-xs text-zinc-500 mt-1">
              Creator-only configuration.
            </div>

          </button>


        </div>


        <div
          id="creator-ui-status"
          class="hidden mt-5 p-3 rounded-xl bg-zinc-950 border border-zinc-800 text-sm text-zinc-400"
        ></div>


        <button
          id="creator-logout-mode"
          class="mt-6 w-full bg-zinc-800 hover:bg-zinc-700 py-3 rounded-xl font-bold"
        >
          Close Creator Mode
        </button>

      </div>

    `;


    document.body.appendChild(panel);


    /*
      CREATE CREATOR BUTTON
    */

    const creatorButton =
      document.createElement("button");

    creatorButton.id =
      "qv37-creator-button";

    creatorButton.className =
      "hidden fixed top-[85px] right-4 z-40 bg-emerald-500 hover:bg-emerald-400 text-black font-bold px-4 py-2 rounded-xl shadow-lg";

    creatorButton.textContent =
      "⚡ Creator";


    document.body.appendChild(
      creatorButton
    );


    /*
      ELEMENTS
    */

    const closeButton =
      document.getElementById(
        "qv37-creator-close"
      );

    const closeModeButton =
      document.getElementById(
        "creator-logout-mode"
      );

    const dashboardButton =
      document.getElementById(
        "creator-dashboard-btn"
      );

    const usersButton =
      document.getElementById(
        "creator-users-btn"
      );

    const appsButton =
      document.getElementById(
        "creator-apps-btn"
      );

    const settingsButton =
      document.getElementById(
        "creator-settings-btn"
      );

    const statusBox =
      document.getElementById(
        "creator-ui-status"
      );


    /*
      SHOW STATUS
    */

    function showCreatorStatus(message) {

      statusBox.textContent =
        message;

      statusBox.classList.remove(
        "hidden"
      );

    }


    /*
      OPEN PANEL
    */

    function openCreatorPanel() {

      if (
        !window.QV37Creator ||
        !window.QV37Creator.isCreator()
      ) {

        showCreatorStatus(
          "Creator verification required."
        );

        return;
      }


      panel.classList.remove(
        "hidden"
      );

    }


    /*
      CLOSE PANEL
    */

    function closeCreatorPanel() {

      panel.classList.add(
        "hidden"
      );

    }


    /*
      CREATOR BUTTON
    */

    creatorButton.addEventListener(
      "click",
      openCreatorPanel
    );


    closeButton.addEventListener(
      "click",
      closeCreatorPanel
    );


    closeModeButton.addEventListener(
      "click",
      closeCreatorPanel
    );


    /*
      DASHBOARD
    */

    dashboardButton.addEventListener(
      "click",
      function () {

        showCreatorStatus(
          "Creator Dashboard will be connected next."
        );

      }
    );


    /*
      USERS
    */

    usersButton.addEventListener(
      "click",
      function () {

        showCreatorStatus(
          "User management will be connected next."
        );

      }
    );


    /*
      GENERATED APPS
    */

    appsButton.addEventListener(
      "click",
      function () {

        showCreatorStatus(
          "Generated Apps management will be connected next."
        );

      }
    );


    /*
      SETTINGS
    */

    settingsButton.addEventListener(
      "click",
      function () {

        showCreatorStatus(
          "Creator settings will be connected next."
        );

      }
    );


    /*
      UPDATE CREATOR BUTTON
    */

    function updateCreatorButton() {

      if (
        window.QV37Creator &&
        window.QV37Creator.isCreator()
      ) {

        creatorButton.classList.remove(
          "hidden"
        );

      } else {

        creatorButton.classList.add(
          "hidden"
        );

        closeCreatorPanel();

      }

    }


    /*
      WATCH CREATOR STATE
    */

    setInterval(
      updateCreatorButton,
      1000
    );


    /*
      INITIAL CHECK
    */

    updateCreatorButton();

  }


  /*
    START
  */

  if (
    document.readyState ===
    "loading"
  ) {

    document.addEventListener(
      "DOMContentLoaded",
      startCreatorUI
    );

  } else {

    startCreatorUI();

  }

})();
