/*
QV37 AI
CREATOR UI — SAFE VERSION

Works with:
- creator.js
- /api/me

IMPORTANT:
Creator authorization is NOT decided by this file.
The server (/api/me) verifies the creator account.
*/

(function () {

"use strict";

/*
WAIT FOR PAGE
*/

function startCreatorUI() {

/*
  DO NOT CREATE DUPLICATES
*/

if (
  document.getElementById(
    "qv37-creator-panel"
  )
) {
  return;
}


/*
  CREATOR PANEL
*/

const panel =
  document.createElement("div");

panel.id =
  "qv37-creator-panel";

panel.className =
  "hidden fixed inset-0 bg-black/80 backdrop-blur-sm z-[100] items-center justify-center p-4";


panel.innerHTML = `

  <div
    class="w-full max-w-2xl bg-zinc-900 border border-zinc-800 rounded-2xl p-6 shadow-2xl"
  >

    <div class="flex items-center justify-between mb-6">

      <div>

        <div class="text-xs text-emerald-400 font-bold">
          QV37 AI
        </div>

        <h2 class="text-2xl font-black">
          Creator Mode
        </h2>

        <p class="text-sm text-zinc-500 mt-1">
          Creator control center
        </p>

      </div>

      <button
        id="qv37-creator-close"
        type="button"
        aria-label="Close Creator Mode"
        class="text-zinc-500 hover:text-white text-2xl"
      >
        ×
      </button>

    </div>


    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">


      <button
        id="creator-dashboard-btn"
        type="button"
        class="text-left bg-zinc-950 border border-zinc-800 hover:border-emerald-500 rounded-xl p-4 transition"
      >

        <div class="text-emerald-400 text-xl">
          📊
        </div>

        <div class="font-bold mt-2">
          Dashboard
        </div>

        <div class="text-xs text-zinc-500 mt-1">
          View creator statistics and system information.
        </div>

      </button>


      <button
        id="creator-users-btn"
        type="button"
        class="text-left bg-zinc-950 border border-zinc-800 hover:border-emerald-500 rounded-xl p-4 transition"
      >

        <div class="text-emerald-400 text-xl">
          👥
        </div>

        <div class="font-bold mt-2">
          Users
        </div>

        <div class="text-xs text-zinc-500 mt-1">
          Manage and inspect QV37 users.
        </div>

      </button>


      <button
        id="creator-apps-btn"
        type="button"
        class="text-left bg-zinc-950 border border-zinc-800 hover:border-emerald-500 rounded-xl p-4 transition"
      >

        <div class="text-emerald-400 text-xl">
          🚀
        </div>

        <div class="font-bold mt-2">
          Generated Apps
        </div>

        <div class="text-xs text-zinc-500 mt-1">
          View applications generated by QV37 AI.
        </div>

      </button>


      <button
        id="creator-settings-btn"
        type="button"
        class="text-left bg-zinc-950 border border-zinc-800 hover:border-emerald-500 rounded-xl p-4 transition"
      >

        <div class="text-emerald-400 text-xl">
          ⚙️
        </div>

        <div class="font-bold mt-2">
          Creator Settings
        </div>

        <div class="text-xs text-zinc-500 mt-1">
          Creator-only configuration.
        </div>

      </button>


    </div>


    <div
      id="creator-ui-status"
      class="hidden mt-5 p-3 rounded-xl bg-zinc-950 border border-zinc-800 text-sm text-zinc-400"
      role="status"
    ></div>


    <button
      id="creator-logout-mode"
      type="button"
      class="mt-6 w-full bg-zinc-800 hover:bg-zinc-700 py-3 rounded-xl font-bold transition"
    >
      Close Creator Mode
    </button>

  </div>

`;


document.body.appendChild(panel);


/*
  CREATOR BUTTON
*/

const creatorButton =
  document.createElement("button");

creatorButton.id =
  "qv37-creator-button";

creatorButton.type =
  "button";

creatorButton.className =
  "hidden fixed top-[85px] right-4 z-40 bg-emerald-500 hover:bg-emerald-400 text-black font-bold px-4 py-2 rounded-xl shadow-lg transition";

creatorButton.textContent =
  "⚡ Creator";

creatorButton.setAttribute(
  "aria-label",
  "Open Creator Mode"
);


document.body.appendChild(
  creatorButton
);


/*
  ELEMENT REFERENCES
*/

const closeButton =
  document.getElementById(
    "qv37-creator-close"
  );

const closeModeButton =
  document.getElementById(
    "creator-logout-mode"
  );

const dashboardButton =
  document.getElementById(
    "creator-dashboard-btn"
  );

const usersButton =
  document.getElementById(
    "creator-users-btn"
  );

const appsButton =
  document.getElementById(
    "creator-apps-btn"
  );

const settingsButton =
  document.getElementById(
    "creator-settings-btn"
  );

const statusBox =
  document.getElementById(
    "creator-ui-status"
  );


/*
  STATUS
*/

function showCreatorStatus(
  message
) {

  statusBox.textContent =
    message;

  statusBox.classList.remove(
    "hidden"
  );

}


function hideCreatorStatus() {

  statusBox.textContent =
    "";

  statusBox.classList.add(
    "hidden"
  );

}


/*
  OPEN PANEL
*/

function openCreatorPanel() {

  if (
    !window.QV37Creator ||
    typeof window.QV37Creator.isCreator !==
      "function"
  ) {

    showCreatorStatus(
      "Creator verification is unavailable."
    );

    return;
  }


  if (
    !window.QV37Creator.isCreator()
  ) {

    showCreatorStatus(
      "Creator verification required."
    );

    return;
  }


  hideCreatorStatus();

  panel.classList.remove(
    "hidden"
  );

  panel.classList.add(
    "flex"
  );

}


/*
  CLOSE PANEL
*/

function closeCreatorPanel() {

  panel.classList.add(
    "hidden"
  );

  panel.classList.remove(
    "flex"
  );

}


/*
  CREATOR BUTTON
*/

creatorButton.addEventListener(
  "click",
  openCreatorPanel
);


closeButton.addEventListener(
  "click",
  closeCreatorPanel
);


closeModeButton.addEventListener(
  "click",
  closeCreatorPanel
);


/*
  CLOSE WHEN CLICKING OUTSIDE
*/

panel.addEventListener(
  "click",
  function (event) {

    if (
      event.target === panel
    ) {

      closeCreatorPanel();

    }

  }
);


/*
  ESCAPE KEY
*/

document.addEventListener(
  "keydown",
  function (event) {

    if (
      event.key === "Escape" &&
      !panel.classList.contains("hidden")
    ) {

      closeCreatorPanel();

    }

  }
);


/*
  DASHBOARD
*/

dashboardButton.addEventListener(
  "click",
  function () {

    if (
      !window.QV37Creator ||
      !window.QV37Creator.isCreator()
    ) {

      closeCreatorPanel();

      return;
    }

    showCreatorStatus(
      "Creator Dashboard is not connected yet."
    );

  }
);


/*
  USERS
*/

usersButton.addEventListener(
  "click",
  function () {

    if (
      !window.QV37Creator ||
      !window.QV37Creator.isCreator()
    ) {

      closeCreatorPanel();

      return;
    }

    showCreatorStatus(
      "User management is not connected yet."
    );

  }
);


/*
  GENERATED APPS
*/

appsButton.addEventListener(
  "click",
  function () {

    if (
      !window.QV37Creator ||
      !window.QV37Creator.isCreator()
    ) {

      closeCreatorPanel();

      return;
    }

    showCreatorStatus(
      "Generated Apps management is not connected yet."
    );

  }
);


/*
  SETTINGS
*/

settingsButton.addEventListener(
  "click",
  function () {

    if (
      !window.QV37Creator ||
      !window.QV37Creator.isCreator()
    ) {

      closeCreatorPanel();

      return;
    }

    showCreatorStatus(
      "Creator Settings are not connected yet."
    );

  }
);


/*
  UPDATE BUTTON
*/

function updateCreatorButton() {

  const creator =
    window.QV37Creator &&
    typeof window.QV37Creator.isCreator ===
      "function" &&
    window.QV37Creator.isCreator();


  if (creator) {

    creatorButton.classList.remove(
      "hidden"
    );

  } else {

    creatorButton.classList.add(
      "hidden"
    );

    closeCreatorPanel();

  }

}


/*
  WATCH CREATOR STATE
*/

const creatorStateWatcher =
  setInterval(
    updateCreatorButton,
    1000
  );


/*
  STOP WATCHER WHEN PAGE IS UNLOADED
*/

window.addEventListener(
  "beforeunload",
  function () {

    clearInterval(
      creatorStateWatcher
    );

  }
);


/*
  INITIAL STATE
*/

updateCreatorButton();

}

/*
START ONLY AFTER DOM
*/

if (
document.readyState ===
"loading"
) {

document.addEventListener(
  "DOMContentLoaded",
  startCreatorUI,
  {
    once: true
  }
);

} else {

startCreatorUI();

}

})();
